### ISSUE TITLE
Can't get or compile go-dqlite anymore

### ISSUE THREAD

**Issue by geosoft1** [canonical/go-dqlite#116]
![Screenshot from 2020-07-11 15-38-04](https://user-images.githubusercontent.com/6298396/87224306-f4e97600-c38c-11ea-88bf-d9c2a3aa725f.png)
This works until some time ago. Thanks.

**Comment by stgraber** [comment]
This means you're using an old version of the dqlite C library. Refresh and rebuild the raft and dqlite C libraries and this will go away.

**Comment by freeekanayaka** [comment]
If you are using the deb packages, I probably need to update the stable PPA, I will do it in the next days.

**Comment by freeekanayaka** [comment]
I've updated the stable PPA, make sure that you have libdqlite-dev 1.5.0 installed and you should be good.

**Comment by geosoft1** [comment]
Now it works. Thanks for quick solve and answer.
