### ISSUE TITLE
Question: can go-dqlite be used as container in a microk8s cluster?

### ISSUE THREAD

**Issue by didier-durand** [canonical/go-dqlite#130]
Hi there,

My question is the following: Is go-dqlite wrappable simply into a container image? Is this image available somewhere?

My use case would then be to deploy this container and query the dqllite database used by microk8s to analyze its content. Indeed, I'd like to make SQL queries like those I am used to with the SQLite CLI: https://sqlite.org/cli.html

Thanks!

DIdier

**Comment by stgraber** [comment]
No. dqlite is an embedded database which in the case of microk8s gets embedded into the API servers.
I don't believe microk8s exposes a REST API endpoint for you to send arbitrary SQL queries to the cluster (like LXD does through `lxd sql`).

dqlite users can allow something like this by exposing their own API which sends requests through go/sql but it's not something you can do on your own if the project you're interacting with didn't put the infrastructure in place.
