### ISSUE TITLE
How to start node with multi machine

### ISSUE THREAD

**Issue by tim0991** [canonical/go-dqlite#156]
Start at machine A， it's works fine

- dqlite-demo -a :8001 -d @1.1.1.1:9001 -v

Start at machine B get error

- dqlite-demo -a :8001 -d @2.2.2.2:9001 -j  1.1.1.1:9001 -v  
   `unsupported protocol 1, attempt with legacy`
- dqlite-demo -a :8001 -d @2.2.2.2:9001 -j  @1.1.1.1:9001 
   `unsupported protocol 1, attempt with legacy` and `write handshake: write unix @->@1.1.1.1:9001: write: broken pipe`  

So what's correct way to create a node join the cluster

**Comment by MathieuBordere** [comment]
When you use regular IPv4 addresses between machines you should use addresses without `@`. `@` is used for unix pipes and can only be used on the same machine.

Something like the following should work:
Machine A: `dqlite-demo -a :8001 -d 1.1.1.1:9001 -v`
Machine B: `dqlite-demo -a :8001 -d 2.2.2.2:9001 -j 1.1.1.1:9001 -v`

**Comment by tim0991** [comment]
As you say, i will get error `create node: failed to set bind address "1.1.1.1:9001": 1`

**Comment by MathieuBordere** [comment]
You need to pick an address that you can actually bind, `1.1.1.1` is just an example, your machine cannot be reached at that IP (same for 2.2.2.2).

Look at the output of `ip a` to determine the IP address of your nodes, and try to bind to those addresses. 

If you want to mess with a cluster on a single machine, you can also bind to localhost.
e.g.

Machine A: 
`dqlite-demo -a :8001 -d 127.0.0.1:9001 -v`
`dqlite-demo -a :8002 -d 127.0.0.1:9002 -j 127.0.0.1:9001 -v`
`dqlite-demo -a :8003 -d 127.0.0.1:9003 -j 127.0.0.1:9001 -v`

**Comment by tim0991** [comment]
Event i change IP address to actually  still not work。

For example  My LAN IP `192.168.0.115`, so i start with `dqlite-demo -a :8001 -d 192.168.0.115:9901`  will get same error

in docker container
![image](https://user-images.githubusercontent.com/26053904/133753174-d238c08b-35e9-4344-b79c-dab6787992c2.png)

**Comment by MathieuBordere** [comment]
Can you try running it on the host instead of in a container?

**Comment by freeekanayaka** [comment]
From the `nc` output you pasted it looks like port `9901` is already in use? That may explain why you can't bind it. Perhaps you have some leftover `dqlite-demo` process that is still running or hasn't released the port?

**Comment by tim0991** [comment]
> Can you try running it on the host instead of in a container?

Yes, it run it in host environment is ok, but why?

**Comment by tim0991** [comment]
thanks guys
