### ISSUE TITLE
Unable to use hostname as bind address

### ISSUE THREAD

**Issue by balchua** [canonical/go-dqlite#158]
Starting dqlite using `hostname:port`, fails to start with this error `failed to set bind address...`

What i am trying to do is to run dqlite inside a pod using `StatefulSet`.

**Comment by freeekanayaka** [comment]
Are you using the `dqlite-demo` app? In that case I think only IP addresses will work not hostnames. To have proper hostnames support you need to use TLS (either modifying the `dqlite-demo` source code or coding your own dqlite-based Go app), see the `app.WithTLS` option and the `app.SimpleTLSConfig` helper.

**Comment by balchua** [comment]
Thanks @freeekanayaka yes i was following the dqlite demo.
I will check those you pointed out. 
I will close this one then.
