### ISSUE TITLE
Outbound connection does not appear to be closed/removed from use when remote side closes it

### ISSUE THREAD

**Issue by tomponline** [canonical/go-dqlite#182]
See https://github.com/lxc/lxd/pull/9891 for more info.

The reproducer is fairly easy:

1. Launch 3 Ubuntu Focal VMs and install the lxd edge snap (sudo snap install lxd --edge).
2. Setup a 3 node LXD cluster (sudo lxd init).
3. Once cluster is up and running, shutdown the leader member cleanly (i.e lxc stop and not lxc stop -f).
4. On the the third member (the one not promoted to leader), check sudo ss -tnp and you should see an outbound LXD 8443 connection to the shutdown member in close-wait state (the logging this PR adds has identified that it is an outbound dqlite and not raft connection).
5. Wait a few seconds and then try running lxc cluster ls on the non-leader member, it should start giving the error at that point.

```
Error: failed to begin transaction: call exec-sql (budget 9.999963394s): receive: header: EOF
```

This doesn't happen 100% of the time, but trying a couple of times should reproduce it, making sure you always test on a non-leader member.

This issue has appeared since we removed the continuous background job for maintaining the LXD event websocket connections (which was causing every member to query the cluster database for members every 1s), somehow by stopping those continuous queries, this has prevented go-dqlite from detecting/handling a remotely closed connection.

My hunch is that its an issue in driverError in go-dqlite, somehow not handling/detecting the EOF error and then not returning driver.ErrBadConn err that would presumably cause the connection to be taken out of use by dqlite.

**Comment by MathieuBordere** [comment]
Possibly related to be implemented in conjunction with this change.

https://pkg.go.dev/database/sql/driver

> All Conn implementations should implement the following interfaces: Pinger, SessionResetter, and Validator. 

```
type SessionResetter interface {
	// ResetSession is called prior to executing a query on the connection
	// if the connection has been used before. If the driver returns ErrBadConn
	// the connection is discarded.
	ResetSession(ctx [context](https://pkg.go.dev/context).[Context](https://pkg.go.dev/context#Context)) [error](https://pkg.go.dev/builtin#error)
}
```
```
type Validator interface {
	// IsValid is called prior to placing the connection into the
	// connection pool. The connection will be discarded if false is returned.
	IsValid() [bool](https://pkg.go.dev/builtin#bool)
}
```
```
