### ISSUE TITLE
more details from dqlite

### ISSUE THREAD

**Issue by logici** [canonical/go-dqlite#195]
enter dqlite shell by`dqlite -s file://xxx -c xxx -k xxxx -f json k8s`. 
I input the `select` command, but I do not know the table name in the db. what should I do to get the table name?
and then, I want to quit the shell, but what should I do to quit the dqlite shell?
```
dqlite> select
Error:  query: incomplete input
dqlite> select *
Error:  query: no tables specified
dqlite> select * from k8s
Error:  query: no such table: k8s
dqlite> .table
Error:  near ".": syntax error
dqlite> .quit
Error:  near ".": syntax error
dqlite> exit
Error:  near "exit": syntax error
dqlite> quit
Error:  near "quit": syntax error
dqlite> .exit
Error:  near ".": syntax error
```

**Comment by freeekanayaka** [comment]
Please try `SELECT name FROM sqlite_schema WHERE type ='table' AND  name NOT LIKE 'sqlite_%'`

**Comment by freeekanayaka** [comment]
Also, what do you want to do exactly?

**Comment by logici** [comment]
Thanks for your reply. Actually, I am using microk8s and it uses the dqlite as storage backend. I want to view the detail in the dqlite, but I not do know how to do it. And these commands like `.cluster` and `.leader` are found in the shell.c code, and the `quit` command should be required. By the way,  do you have some references and docs about dqlite?  there is little information I can find.

**Comment by freeekanayaka** [comment]
See https://www.dqlite.io

**Comment by logici** [comment]
Thanks. Also, I means that it is best for me to have some client guides. It is difficult for me to use the client. I do not know what command I can use in the dqlite shell. Maybe, I lack some knowledge.

**Comment by freeekanayaka** [comment]
The client just lets you run normal SQL queries, not much more except perhaps the special `.cluster` and `.leader` commands that you mention. There's not much to learn about it.

What problem are you trying to solve? You should not need any knowledge of this to use microk8s.

**Comment by logici** [comment]
When a cross region node join to a cluster, I encounter some problems that are like data synchronization. But I am not sure actually. I just want to research all aspects. Anyway, thanks for your reply.
