### ISSUE TITLE
Allow WithExternalConn use any net.Conn instance

### ISSUE THREAD

**Issue by Zxilly** [canonical/go-dqlite#238]
I wonder if that is possible to allow `WithExternalConn` use any `net.Conn`.  

As for now, it assume the connection is a `net.TCPConn` or `tls.Conn`.  And there are many behaviors bind to tcp.

**Comment by MathieuBordere** [comment]
dqlite and the underlying raft library are designed assuming that the transport is reliable, you could use any other reliable `net.Conn`.

**Comment by Zxilly** [comment]
yes,  I'd like to use quic as the transport layer for the dqlite.  But as for now, go-dqlite has a function called extractTcpConn, and it cannot support other kind net.Conn.
It will also try to use syscall to set tcp keepalive params.

**Comment by MathieuBordere** [comment]
Ok, thanks for pointing that out, I'll make an issue out of it.

**Comment by Zxilly** [comment]
And 
https://github.com/canonical/go-dqlite/blob/251e831db80e50bb6a54431e31529d12aa1291c5/app/app.go#L275-L280
will lead to handshake failure on transport other than http.
