### ISSUE TITLE
Expose an operation to remove a node from the cluster

### ISSUE THREAD

**Issue by cole-miller** [canonical/go-dqlite#250]
We've had a request from the Juju team to add an API in go-dqlite for removing a node from the cluster configuration (as opposed to just demoting it, which automatic role management should handle if the node has become inactive). We already have this operation in the dqlite wire protocol, so it's just a matter of finding the appropriate place to add it in go-dqlite and making sure it doesn't interact badly with anything else.

**Comment by freeekanayaka** [comment]
Should be:

https://pkg.go.dev/github.com/canonical/go-dqlite@v1.11.9/client#Client.Remove

and possibly:

https://pkg.go.dev/github.com/canonical/go-dqlite@v1.11.9/app#App.Leader

to automatically get a `Client` object connected to the cluster leader.
