### ISSUE TITLE
EOF errors on connect when using external connection with `http.Serve`

### ISSUE THREAD

**Issue by masnax** [canonical/go-dqlite#305]
As a result of #302, I realized microcluster was not properly handling the context it received from `go-dqlite` when the dial func is called.

However, [upon properly propagating this context](https://github.com/canonical/microcluster/pull/166), I began to notice lots of these errors constantly on each heartbeat:
```
2024/07/10 15:57:18 http: TLS handshake error from 127.0.0.1:60120: EOF
2024/07/10 15:57:26 http: TLS handshake error from 127.0.0.1:48016: read tcp 127.0.0.1:9000->127.0.0.1:48016: read: connection reset by peer
```

`http.Serve` logs TLS handshake errors on line 1935 here: https://go.dev/src/net/http/server.go

This looks to be connected to [this cancel() call](https://github.com/canonical/go-dqlite/blob/95f620cdb3f17d65af0eb21a5849cdd210028000/internal/protocol/connector.go#L219) which cancels all active connections using the dial func.  

The errors are too generic to just ignore, so I was thinking if it would be cleaner to simply leave the connections alive and use a mutex to avoid starting new connections when the leader is found to avoid this noise?

**Comment by cole-miller** [comment]
Oh, that's unfortunate. Not passing the cancellable context down into our Dial call will result in some wasted work, but worth it if there's no other way to avoid the log spam.

I'll try to put together a patch for this later today.
