### ISSUE TITLE
production-readiness?

### ISSUE THREAD

**Issue by the-oaks** [canonical/go-dqlite#43]
I know in the README page you mentioned this is currently in beta, may I ask if this is accurate or we are production-ready? thanks

**Comment by freeekanayaka** [comment]
We're closer to production-ready than to beta. We're going to release and launch dqlite 1.0 this week. So please stay tuned!

FWIW dqlite/go-dqlite are already used in production by users of [LXD](http://github.com/lxc/lxd/), which uses dqlite under the hood.

**Comment by freeekanayaka** [comment]
The readme is going to be updated soon, as well.

**Comment by the-oaks** [comment]
thanks, look forward to the release!

**Comment by freeekanayaka** [comment]
I tagged both [go-dqlite](https://github.com/canonical/go-dqlite) and [dqlite](https://github.com/canonical/dqlite) with v1.0.0.

See also the associated web site: https://dqlite.io

The API will be stable from now on, and future release will be backward compatible.
