### ISSUE TITLE
error message when trying to build/install the demo app

### ISSUE THREAD

**Issue by the-oaks** [canonical/go-dqlite#47]
hi, I was following the readme and try to build/install the demo app, but I keep getting the following error, could you please advise on what need to be done or what can be the most likely thing I am missing? thanks 

/go/src/github.com/canonical/go-dqlite/internal/bindings/errors.go:33:27: could not determine kind of name for C.SQLITE_IOERR_LEADERSHIP_LOST

**Comment by freeekanayaka** [comment]
It means you are not using the headers of the patched SQLite. If you are on Ubuntu/Debian I suggest to get the libsqlite3-dev package from the [PPA](https://launchpad.net/~dqlite/+archive/ubuntu/v1) or build github.com/canonical/sqlite and make sure sqlite3.h is in your import path.

**Comment by the-oaks** [comment]
thanks for the hint, it was an issue with the C_PATH, my existing sqlite3.h somehow get picked up before the installed one.
