### ISSUE TITLE
errors are from internal package

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/go-dqlite#55]
From what I see the errors from the SQL driver are of type bindings.Error.  bindings is an internal package so it is not possible for the caller to cast the error and read the actual error code from SQLite.  Right now I need to detect a unique constraint error.

**Comment by freeekanayaka** [comment]
There's a type alias in the driver package, see [here](https://github.com/canonical/go-dqlite/blob/master/driver/driver.go#L45).

I've just pushed a PR with an integration test to check that it works correctly, see #56. The only caveat is that for now go-dqlite itself doesn't have a list of SQLite error codes, so you might want to import the ones defined in go-sqlite3 (as the test does). Also note that dqlite reports extended error codes by default, see the relevant SQLite [docs](https://www.sqlite.org/rescode.html).
