### ISSUE TITLE
Use of internal package github.com/canonical/go-dqlite/internal/bindings not allowed,,,

### ISSUE THREAD

**Issue by teran-mckinney** [canonical/go-dqlite#58]
Not having any luck building this.

```
$ go version
go version go1.13.4 linux/amd64
$ go build
config.go:7:2: use of internal package github.com/canonical/go-dqlite/internal/bindings not allowed
```

**Comment by freeekanayaka** [comment]
Please try:

```
sudo add-apt-repository -y ppa:dqlite/stable
sudo apt install dqlite libdqlite-dev
go get -tags libsqlite3 github.com/canonical/go-dqlite
```

If you are not on a Debian/Ubuntu system, you'll need to install the dqlite C library [by hand](https://github.com/canonical/dqlite#build).

**Comment by teran-mckinney** [comment]
Worked, thank you! Already did the first two, just didn't want to build in a relative way I guess. Or maybe I needed `go build -tags libsqlite3`, hmm.

**Comment by freeekanayaka** [comment]
Yes, you always need to pass ```-tags libsqlite3```.
