### ISSUE TITLE
"$GOPATH not set" when running go install -tags libsqlite3.

### ISSUE THREAD

**Issue by 179416326** [canonical/go-dqlite#64]
Hi, freeekanayaka, sorry for the disturb again, i have built dqlite by hand (also tried for apt install), but countered the following problems. So what else do i need to set $GOPATH?

zz@zz-virtual-machine:~/canonical/go-dqlite-master$ go version
go version go1.6.2 linux/amd64

zz@zz-virtual-machine:~/canonical/go-dqlite-master$ go install -tags libsqlite3 ./cmd/dqlite-demo
cmd/dqlite-demo/add.go:4:2: cannot find package "context" in any of:
        /usr/lib/go-1.6/src/context (from $GOROOT)
        ($GOPATH not set)
cmd/dqlite-demo/start.go:12:2: cannot find package "github.com/canonical/go-dqlite" in any of:
        /usr/lib/go-1.6/src/github.com/canonical/go-dqlite (from $GOROOT)
        ($GOPATH not set)
cmd/dqlite-demo/add.go:9:2: cannot find package "github.com/canonical/go-dqlite/client" in any of:
        /usr/lib/go-1.6/src/github.com/canonical/go-dqlite/client (from $GOROOT)
        ($GOPATH not set)
cmd/dqlite-demo/benchmark.go:9:2: cannot find package "github.com/canonical/go-dqlite/driver" in any of:
        /usr/lib/go-1.6/src/github.com/canonical/go-dqlite/driver (from $GOROOT)
        ($GOPATH not set)
cmd/dqlite-demo/add.go:10:2: cannot find package "github.com/pkg/errors" in any of:
        /usr/lib/go-1.6/src/github.com/pkg/errors (from $GOROOT)
        ($GOPATH not set)
cmd/dqlite-demo/add.go:11:2: cannot find package "github.com/spf13/cobra" in any of:
        /usr/lib/go-1.6/src/github.com/spf13/cobra (from $GOROOT)
        ($GOPATH not set)

**Comment by freeekanayaka** [comment]
You don't need to set ```GOPATH```, unless you want a custom location for your Go code.

You need to put the source tree of go-dqlite in the location where go expects it to be:

```bash
mkdir -p ~/go/src/github.com/canonical
mv ~/canonical/go-dqlite-master ~/go/src/github.com/canonical/go-dqlite
cd ~/go/src/github.com/canonical/go-dqlite/cmd/dqlite-demo
go build -tags libsqlite3
```

**Comment by 179416326** [comment]
Problem countered：
cmd/dqlite-demo/add.go:4:2: cannot find package "context" in any of:
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /home/zz/go/src/context (from $GOPATH)
        /home/zz/go/src/github.com/canonical/go-dqlite/src/context

**Comment by freeekanayaka** [comment]
Go 1.6 is very old and not anymore supported by the Go team. Please Use 1.10 or higher.
