### ISSUE TITLE
Cannot find package "context" 

### ISSUE THREAD

**Issue by 179416326** [canonical/go-dqlite#65]
Problem countered：
 go install -tags libsqlite3 ./cmd/dqlite-demo
cmd/dqlite-demo/add.go:4:2: cannot find package "context" in any of:
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /home/zz/go/src/context (from $GOPATH)
        /home/zz/go/src/github.com/canonical/go-dqlite/src/context

_Originally posted by @179416326 in https://github.com/canonical/go-dqlite/issues/64#issuecomment-563682765_

**Comment by 179416326** [comment]
zz@zz-virtual-machine:~/go/src/github.com/canonical/go-dqlite$ go env
GOARCH="amd64"
GOBIN="/usr/lib/go-1.6/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zz/go:/home/zz/go/src/github.com/canonical/go-dqlite"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by 179416326** [comment]
After install go1.13, the "Cannot find package "context"" problem solved, but came new problem:

zz@zz-virtual-machine:~/go/src/github.com/canonical/go-dqlite$ go install -tags libsqlite3 ./cmd/dqlite-demo
import cycle not allowed
package github.com/canonical/go-dqlite/cmd/dqlite-demo
        imports context
        imports errors
        imports internal/reflectlite
        imports runtime
        imports internal/bytealg
        imports internal/cpu
        imports runtime

**Comment by freeekanayaka** [comment]
Please try to create a file called ```~/main.go``` in your home directory, with this content:

```go
package main

import (
	"context"
	"fmt"
)

func main() {
	fmt.Println(context.Background())
}
```

and then run ```go run main.go``` from your home directory.

If it fails in the same way, it probably means that you have mixed up your Go 1.6 and Go 1.13 installations.

**Comment by 179416326** [comment]
dqlite-demo binary is installed, but something wrong when start :

root@zz-virtual-machine:/home/zz/go/src/github.com/canonical/go-dqlite# dqlite-demo start 1
dqlite-demo: symbol lookup error: /usr/local/lib/libraft.so.0: undefined symbol: __asan_option_detect_stack_use_after_return

**Comment by freeekanayaka** [comment]
You probably compiled the raft library using ```./configure --enable-sanitize```, which is not supported when using Go, and should only be used for development of raft itself. Please use just ```./configure```, or ```./configure --enable-debug```.

**Comment by 179416326** [comment]
Thanks a lot, now running dqlite-demo well.

**Comment by 179416326** [comment]
Consumed a lot of time on GO, if CLIENT written in C will be perfect!

**Comment by freeekanayaka** [comment]
C client would be nice indeed, but at the moment I don't have the time to write it.
