### ISSUE TITLE
is there any python3driver ? 

### ISSUE THREAD

**Issue by MyraBaba** [canonical/go-dqlite#81]
is there any python3driver ?

**Comment by freeekanayaka** [comment]
Not that I know of.

**Comment by MyraBaba** [comment]
so canonical promoting Go lang then..  :(

**Comment by freeekanayaka** [comment]
Not really, it's just that there's currently no business reason for writing a Python 3 client, so resources are not being allocated for that. Nothing to do with Go vs Python, it's just that the only consumer of dqlite at Canonical is LXD, which is in Go.

Contributions for writing a Python client would be welcome, you can find the protocol documentation on https://dqlite.io.

**Comment by MyraBaba** [comment]
thanks..

will look into it and try one.

**Comment by stgraber** [comment]
Closing as this is an issue on the Go binding.
We have plans to implement a generic C client in https://github.com/canonical/dqlite which could then be used by anyone wanting to make a traditional binding without having to re-implement too much of the client logic.

**Comment by stgraber** [comment]
https://github.com/canonical/dqlite/issues/291
