### ISSUE TITLE
segmentation fault during node creation

### ISSUE THREAD

**Issue by jeromegn** [canonical/go-dqlite#93]
I've been trying to create rust bindings for dqlite, but kept stumbling on issues. I figured I'd try go-dqlite to see if my system was maybe misconfigured.

I tried running the demo app but I immediatly got this segfault:

```
$ go run ./cmd/dqlite-demo/dqlite-demo.go -a 127.0.0.1:5005 -db 127.0.0.1:5006
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x9f24b4, 0x2a)
        /usr/lib/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/lib/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 1 [syscall]:
runtime.cgocall(0x810328, 0xc0000db8b8, 0xc0000100b8)
        /usr/lib/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0000db888 sp=0xc0000db850 pc=0x40b95b
github.com/canonical/go-dqlite/internal/bindings._Cfunc_dqlite_node_create(0x2dc171858c3155be, 0x126b8a0, 0x126b8c0, 0xc0000100b8, 0xc000000000)
        _cgo_gotypes.go:137 +0x4d fp=0xc0000db8b8 sp=0xc0000db888 pc=0x7869ed
github.com/canonical/go-dqlite/internal/bindings.NewNode.func3(0x2dc171858c3155be, 0x126b8a0, 0x126b8c0, 0xc0000100b8, 0x0)
        /home/jerome/go/src/github.com/canonical/go-dqlite/internal/bindings/server.go:116 +0x89 fp=0xc0000db8f0 sp=0xc0000db8b8 pc=0x788729
github.com/canonical/go-dqlite/internal/bindings.NewNode(0x2dc171858c3155be, 0x7ffe237fc194, 0x1, 0xc000026620, 0x12, 0x0, 0x0, 0x0)
        /home/jerome/go/src/github.com/canonical/go-dqlite/internal/bindings/server.go:116 +0x10e fp=0xc0000db978 sp=0xc0000db8f0 pc=0x78769e
github.com/canonical/go-dqlite.New(0x2dc171858c3155be, 0x7ffe237fc194, 0x1, 0xc000026620, 0x12, 0xc0000dbb60, 0x2, 0x2, 0x100000000000000, 0x0, ...)
        /home/jerome/go/src/github.com/canonical/go-dqlite/node.go:56 +0xbe fp=0xc0000db9e8 sp=0xc0000db978 pc=0x7a634e
github.com/canonical/go-dqlite/app.New(0xc000026620, 0x12, 0xc0000dbce8, 0x2, 0x2, 0x0, 0x8000103, 0x0)
        /home/jerome/go/src/github.com/canonical/go-dqlite/app/app.go:104 +0x42b fp=0xc0000dbc10 sp=0xc0000db9e8 pc=0x7a9a4b
main.main.func1(0xc0000bcb00, 0xc000034480, 0x1, 0x4, 0x0, 0x0)
        /home/jerome/go/src/github.com/canonical/go-dqlite/cmd/dqlite-demo/dqlite-demo.go:37 +0x1b3 fp=0xc0000dbd38 sp=0xc0000dbc10 pc=0x80eb23
github.com/spf13/cobra.(*Command).execute(0xc0000bcb00, 0xc0000200b0, 0x4, 0x4, 0xc0000bcb00, 0xc0000200b0)
        /home/jerome/go/src/github.com/spf13/cobra/command.go:842 +0x453 fp=0xc0000dbe10 sp=0xc0000dbd38 pc=0x7ff403
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bcb00, 0x9dfa62, 0x2, 0x0)
        /home/jerome/go/src/github.com/spf13/cobra/command.go:950 +0x349 fp=0xc0000dbee8 sp=0xc0000dbe10 pc=0x7fff29
github.com/spf13/cobra.(*Command).Execute(...)
        /home/jerome/go/src/github.com/spf13/cobra/command.go:887
main.main()
        /home/jerome/go/src/github.com/canonical/go-dqlite/cmd/dqlite-demo/dqlite-demo.go:106 +0x384 fp=0xc0000dbf88 sp=0xc0000dbee8 pc=0x80e294
runtime.main()
        /usr/lib/go/src/runtime/proc.go:203 +0x212 fp=0xc0000dbfe0 sp=0xc0000dbf88 pc=0x43dd32
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000dbfe8 sp=0xc0000dbfe0 pc=0x46b271
exit status 2
```

I'm running go 1.14.2 on Arch linux. I am using dqlite 1.4.1 and sqlite-replication 3.31.1.4, installed via pacman. I had to set the following environment variables to even get it to run at all:

```
export CGO_CFLAGS="-I/usr/include/sqlite-replication/"
export CGO_LDFLAGS="-L/usr/lib/sqlite-replication/"
export LD_LIBRARY_PATH=/usr/lib/sqlite-replication/
```

Am I doing something wrong?

**Comment by stgraber** [comment]
Try passing `-tags libsqlite3`? I don't know if there's some magic in this Go application to use the share library, but if not, without that tag, you may end up using an incorrect libsqlite3.

**Comment by freeekanayaka** [comment]
What @stgraber says.

Quoting https://github.com/canonical/go-dqlite/#demo :

"
or build the dqlite C library and its dependencies from source, as described here, and then run:

```
go install -tags libsqlite3 ./cmd/dqlite-demo
```
"

**Comment by jeromegn** [comment]
That's interesting. I don't know how that works :)

```
$ go install -tags libsqlite3 ./cmd/dqlite-demo

$ dqlite-demo -a 127.0.0.1:5005 -db 127.0.0.1:5006
Error: failed to set bind address
```

^^ it got rid of the segfault, but now I believe I'm getting the same issue I have in my rust project, related to: https://github.com/canonical/dqlite/issues/218

**Comment by freeekanayaka** [comment]
Would it be possible for you to clone the C dqlite repository, build it from source and try the C code snippet I pasted in canonical/dqlite#218 ?

If that does work, then it might be something odd in the arch package. If that does not work I'll send you a patch to debug the issue.

**Comment by jeromegn** [comment]
I was currently replying to the other issue :) The code you pasted in https://github.com/canonical/dqlite/issues/218 works fine on my machine. Which is very puzzling.

I've compiled the library locally before to try it out (added the debug flag to try and figure out why this would be happening too), but it showed the same behavior. (I had completely uninstalled the arch package to make sure it wasn't being used)

I'll try again

**Comment by jeromegn** [comment]
I just did again.

Now I get slightly different behaviour:

```
$ go run -tags libsqlite3 ./cmd/dqlite-demo/dqlite-demo.go -a 127.0.0.1:5005 -db 127.0.0.1:5006
# github.com/canonical/go-dqlite/internal/bindings
/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to `sqlite3_wal_replication_frames'
/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to `sqlite3_wal_replication_enabled'
/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to `sqlite3_wal_replication_leader'
/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to `sqlite3_wal_replication_undo'
/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to `sqlite3_wal_replication_unregister'
/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to `sqlite3_wal_replication_follower'
/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to `sqlite3_wal_replication_register'
collect2: error: ld returned 1 exit status
```

so I set some env vars:

```
$ LD_LIBRARY_PATH=/usr/lib/sqlite-replication/:/usr/local/lib/ CGO_LDFLAGS=-L/usr/lib/sqlite-replication/ go run -tags libsqlite3 ./cmd/dqlite-demo/dqlite-demo.go -a 127.0.0.1:5005 -db 127.0.0.1:5006
Error: failed to set bind address
```

(dqlite compiled from source and using `make install` installed the lib in /usr/local/lib by default. The arch package I installed before put it in /usr/lib, so I have to specific that env var to get to the new package)

**Comment by freeekanayaka** [comment]
If that code works, it means there's something odd in the arch package. Maybe it's actually not v1.4.1?

Instead of `go run` try to use `go build`, then launch the compiled binary using the env variables you pasted. I'm not totally sure `go run` passes those envs across.

If that still does not work, try to locate the `libdqlite.so.0.0.1` file shipped in your arch package and replace it with the one you built by hand (you find it under the `./libs` directory of your git checkout).

**Comment by jeromegn** [comment]
The code in https://github.com/canonical/dqlite/issues/218 works with both the arch package and the lib compiled from source. So this doesn't look like my install is wrong.

Since there are no segfaults and no undefined symbols errors, I'm assuming it's using the correct libraries. If it's not using the right sqlite3 lib, I usually get things like `/usr/bin/ld: /usr/local/lib/libdqlite.so: undefined reference to 'sqlite3_wal_replication_frames'`. If it can't find dqlite, I get `dqlite-demo: error while loading shared libraries: libdqlite.so.0: cannot open shared object file: No such file or directory`

As far as I can tell both the pre-compiled lib from the arch package and my own compiled-from-source lib have the same behavior: the code from https://github.com/canonical/dqlite/issues/218 works perfectly, the go-dqlite demo "failed to set bind address" and my own rust implementation also fails to set the bind address.

The initial segfault I reported in this issue was fixed by adding `-tags libsqlite3` to either `go run`, `go build` or `go install`.

This is very mysterious.

**Comment by freeekanayaka** [comment]
> As far as I can tell both the pre-compiled lib from the arch package and my own compiled-from-source lib have the same behavior: the code from [canonical/dqlite#218](https://github.com/canonical/dqlite/issues/218) works perfectly, the go-dqlite demo "failed to set bind address" and my own rust implementation also fails to set the bind address.

Please can you try with:

```
dqlite-demo  -a 127.0.0.1:5005 --db 127.0.0.1:5006
```

note the **--db** (double dash) instead of **-db** (single dash). I can reproduce your problem with the single dash, so it might be an argument parsing issue.

**Comment by jeromegn** [comment]
That does fix it.
